name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.vscode/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.vscode/**'

jobs:
  build:
    name: Build & Test
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - name: Build
        run: yarn --skip-integrity-check --network-timeout 100000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Check for uncommitted changes in yarn.lock
        run: |
          if git diff --name-only | grep -q "^yarn.lock"; then
            echo "::error::The yarn.lock file has uncommitted changes!"
            exit 1
          fi
      - name: Build electron
        run: yarn electron build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Build browser
        run: yarn browser build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
  lint:
    name: Lint
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - name: Install
        run: |
          yarn install --ignore-scripts
          yarn compile
      - name: Create eslint json report
        run: |
          yarn lint:ci
      - name: Create summary
        if: always()
        run: |
          npm_config_yes=true npx github:10up/eslint-json-to-md#82ff16b --path ./eslint_report.json --output ./eslint_report.md
          cat eslint_report.md >> $GITHUB_STEP_SUMMARY
