name: Theia Compatibility

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 8 AM UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        theia_version: [1.60.0, latest]
    env:
      STANDALONE_URL: none'
      GLSP_SERVER_PORT: '8081'
      GLSP_SERVER_PLAYWRIGHT_MANAGED: 'false'
      GLSP_WEBSOCKET_PATH: 'workflow'
      THEIA_URL: 'http://localhost:3000'
      VSCODE_VSIX_ID: 'none'
      VSCODE_VSIX_PATH: 'none'
      GLSP_SERVER_DEBUG: 'true'
      GLSP_SERVER_TYPE: 'node'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: 'theia-integration'
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: 'eclipse-glsp/glsp-playwright'
          path: 'glsp-playwright'
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20.x
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'
      - name: Build
        run: |
          cd theia-integration
          yarn --skip-integrity-check --network-timeout 100000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Change theia version
        run: |
          cd theia-integration
          yarn change:theia-version ${{ matrix.theia_version }}
      - name: Clean yarn.lock
        run: |
          cd theia-integration
          rm -f yarn.lock
      - name: Build electron
        run: |
          cd theia-integration
          yarn electron build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Build browser
        run: |
          cd theia-integration
          yarn --skip-integrity-check --network-timeout 100000 && yarn browser build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Build Playwright
        run: |
          cd glsp-playwright
          yarn
      - name: Start Browser App
        run: |
          cd theia-integration
          yarn browser start &
      - name: Run Playwright tests
        id: run_playwright_tests
        run: |
          cd glsp-playwright
            yarn test:theia
      - name: Upload Playwright report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: playwright-report-compat-${{ matrix.theia_version }}
          path: glsp-playwright/examples/workflow-test/playwright-report/
